[project]
name = "python-agents"
version = "0.1.0"
description = "Python Agents Projects"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-core>=0.5.5",
    "autogen-ext[grpc]>=0.5.5",
]
